title: "Juan Manuel & Nerina Curbelo"
description: "Sitio personal y ministerial de Juan Manuel y Nerina Curbelo."
lang: es
url: "https://juanmanuelynerinacurbelo.com"
baseurl: ""
timezone: America/Argentina/Mendoza
permalink: pretty

plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
